server.port=${CHAT_SERVICE_PORT:8082}

spring.data.mongodb.host=${SPRING_DATA_MONGODB_HOST:localhost}
spring.data.mongodb.port=${SPRING_DATA_MONGODB_PORT:27017}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:chat_mongodb}
spring.data.mongodb.username=${SPRING_DATA_MONGODB_USERNAME}
spring.data.mongodb.password=${SPRING_DATA_MONGODB_PASSWORD}
spring.data.mongodb.authentication-database=${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}

# Configuracoes do RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=${RABBITMQ_DEFAULT_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:guest}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:guest}

# Configuracoes do Redis
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}

# Configuracoes do STOMP Relay
relay.host=rabbitmq
relay.port=${RELAY_PORT:61613}

# JWT Secret
jwt.secret=${JWT_SECRET}

# Configuracoes do Eureka Client
eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}
